# Programming Assignment No. 2 :  Numerical Python  ###

---

This repository includes the solution to different programming problems involving the Numpy or the Numerical Python Library. The assignment includes the making of "Normalization" and "Divisible by 3".

## Number 1 : Normalization problem ###
Normalization is one of the most basic preprocessing techniques in
data analytics. This involves centering and scaling proces.

In this code, we will print a 5x5 array with random values and its normalized versions

In [47]:
#imports the library of numpy to access
import numpy as np
# Inputs random numbers in a 5x5 array
X = np.random.rand(5,5) 

# uses the mean formula to find the mean of the array
Xmean = np.mean(X) 
#calculates for the std of the array
Xstd = np.std(X) 
#formula for the normalized array
X_normalized = (X-Xmean)/Xstd 

#Prints the original values of the 5x5 array
print("Your original values are: \n", X) 

#prints the normalized value
print("The normalized value are: \n", X_normalized) 

#saves the array in the format of X_normalized.npy
np.save("X_normalized.npy", X_normalized) 


Your original values are: 
 [[0.43614089 0.42199299 0.18745598 0.83643213 0.31372984]
 [0.01226685 0.24249692 0.03999078 0.82628442 0.02496891]
 [0.42870266 0.72847798 0.68446487 0.71092214 0.77260273]
 [0.71811088 0.44490057 0.81807432 0.75203574 0.6451391 ]
 [0.29750212 0.8596331  0.81914881 0.95882535 0.65712148]]
The normalized value are: 
 [[-0.38607405 -0.43602229 -1.26403976  1.0271278  -0.81823822]
 [-1.88253345 -1.06972134 -1.78465595  0.991302   -1.83768967]
 [-0.41233426  0.64600279  0.49061741  0.58402307  0.80178232]
 [ 0.60940242 -0.35514861  0.96231676  0.7291719   0.35178037]
 [-0.87552911  1.10903729  0.9661102   1.45922903  0.39408335]]


---

## Number 2 : Division by 3 ###
In this code, it will generate a 10x10 positive integers that are squared. it will then find the elements that are divisible by 3 and will print the numbers that satisfty the condition also.

In [49]:
#imports the library of numpy to access
import numpy as np 
#The .arange() function will create a 1x1 array ranging from 1 to 100 in a single row
array_100 = np.arange(1,101) 
#The .reshape() will reshape the array into a 10x10 array
array= array_100.reshape(10,10) 

#the .square() function will square all the values inside the array
x= np.square(array)
#outputs the square of the numbers
print("The square of the numbers 1-100 are : \n", x)

#checks for the numbers in the array if they are divisible by 3
divby3 = x[x%3 == 0]
#outputs the numbers that are divisible by 3
print("The numbers in the array that are divisble by 3 are :\n",divby3) 

#saves the result as div_by_3.npy
np.save("div_by_3.npy", divby3) 



The square of the numbers 1-100 are : 
 [[    1     4     9    16    25    36    49    64    81   100]
 [  121   144   169   196   225   256   289   324   361   400]
 [  441   484   529   576   625   676   729   784   841   900]
 [  961  1024  1089  1156  1225  1296  1369  1444  1521  1600]
 [ 1681  1764  1849  1936  2025  2116  2209  2304  2401  2500]
 [ 2601  2704  2809  2916  3025  3136  3249  3364  3481  3600]
 [ 3721  3844  3969  4096  4225  4356  4489  4624  4761  4900]
 [ 5041  5184  5329  5476  5625  5776  5929  6084  6241  6400]
 [ 6561  6724  6889  7056  7225  7396  7569  7744  7921  8100]
 [ 8281  8464  8649  8836  9025  9216  9409  9604  9801 10000]]
The numbers in the array that are divisble by 3 are :
 [   9   36   81  144  225  324  441  576  729  900 1089 1296 1521 1764
 2025 2304 2601 2916 3249 3600 3969 4356 4761 5184 5625 6084 6561 7056
 7569 8100 8649 9216 9801]
